source 'https://cdn.cocoapods.org/'
#source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

platform :ios, '9.0'

target 'WXNetworking_Example' do
  
  #pod 'AFNetworking'
  
  pod 'WXNetworking', :path => '../'

end
